# Generated by Django 5.2.1 on 2026-08-07 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_colour_product_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='product_image',
        ),
    ]
