# Generated by Django 5.2.1 on 2026-08-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='store_credit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
