# Generated by Django 5.2.1 on 2026-07-30 10:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('PROFILE_PHOTO', 'Profile Photo'), ('ID_PROOF', 'ID Proof'), ('AADHAAR_FRONT', 'Aadhaar Card (Front)'), ('AADHAAR_BACK', 'Aadhaar Card (Back)'), ('PAN_CARD', 'PAN Card'), ('ADDRESS_PROOF', 'Address Proof'), ('OTHER', 'Other Supporting Document')], max_length=20)),
                ('file', models.FileField(upload_to='user_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_documents',
            },
        ),
    ]
