# Generated by Django 5.2.1 on 2026-07-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='document_type',
            field=models.CharField(choices=[('PROFILE_PHOTO', 'Profile Photo'), ('ID_PROOF', 'ID Proof')], max_length=20),
        ),
    ]
