# Generated by Django 5.2.1 on 2026-07-30 11:19

import apps.accounts.models
import apps.accounts.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_address_alter_userdocument_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='document_type',
            field=models.CharField(choices=[('PROFILE_PHOTO', 'Profile Photo'), ('AADHAAR', 'Aadhaar'), ('PAN', 'PAN'), ('ADDRESS_PROOF', 'Address Proof'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='file',
            field=models.FileField(upload_to=apps.accounts.models.user_directory_path, validators=[apps.accounts.validators.validate_file_extension, apps.accounts.validators.validate_file_size]),
        ),
    ]
