# Generated by Django 5.2.1 on 2026-08-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SUB_ADMIN', 'Sub-Admin'), ('CASHIER', 'Cashier'), ('STORE_STAFF', 'Store Staff')], default='STORE_STAFF', max_length=20),
        ),
    ]
