# Generated by Django 5.2.16 on 2026-07-25 04:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name_snapshot', models.CharField(max_length=255)),
                ('hsn_code_snapshot', models.CharField(max_length=50)),
                ('gst_rate_snapshot', models.DecimalField(decimal_places=2, max_digits=5)),
                ('original_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('final_selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('final_line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.product')),
            ],
            options={
                'db_table': 'invoice_items',
            },
        ),
    ]
