# Generated by Django 5.2.1 on 2026-08-06 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoiceitem_serialized_item_cart_cartitem_invoice_and_more'),
        ('inventory', '0002_branchstock_reserved_quantity_serializeditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='serialized_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='inventory.serializeditem'),
        ),
    ]
