# Generated by Django 5.2.1 on 2026-08-10 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_cartitem_serialized_item'),
        ('branches', '0002_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='counter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='branches.counter'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='counter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='branches.counter'),
        ),
    ]
