# Generated by Django 5.2.1 on 2026-08-11 05:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_cart_counter_invoice_counter'),
        ('branches', '0002_counter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='credit_applied',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='ExchangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved & Stock Updated'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Exchange Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_exchanges', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='branches.branch')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='exchange_requests', to='billing.invoice')),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='billing.invoiceitem')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='exchange_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exchange_requests',
            },
        ),
    ]
