# Generated by Django 5.2.1 on 2026-08-12 09:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_invoice_credit_applied_exchangerequest'),
        ('customers', '0002_customer_store_credit'),
        ('products', '0006_rename_image_product_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='promo_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('offer_type', models.CharField(choices=[('PERCENTAGE', 'Percentage Discount'), ('FLAT', 'Flat Amount Discount'), ('BOGO', 'Buy One Get One'), ('BUY_X_GET_Y', 'Buy X Get Y')], max_length=20)),
                ('offer_theme', models.CharField(choices=[('SEASONAL', 'Seasonal Offer'), ('FESTIVAL', 'Festival Offer'), ('CLEARANCE', 'Clearance Offer'), ('SLOW_MOVING', 'Slow-Moving Stock Offer'), ('LOYALTY', 'Loyalty Discount'), ('GENERAL', 'General Offer')], default='GENERAL', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('buy_quantity', models.IntegerField(default=1)),
                ('get_quantity', models.IntegerField(default=0)),
                ('coupon_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('usage_limit', models.IntegerField(default=0, help_text='0 means unlimited')),
                ('times_used', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_brands', models.ManyToManyField(blank=True, related_name='offers', to='products.brand')),
                ('applicable_categories', models.ManyToManyField(blank=True, related_name='offers', to='products.category')),
                ('applicable_customers', models.ManyToManyField(blank=True, related_name='specific_offers', to='customers.customer')),
                ('applicable_products', models.ManyToManyField(blank=True, related_name='offers', to='products.product')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_offers', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'offers',
            },
        ),
        migrations.CreateModel(
            name='OfferUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_applied', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_usages', to='customers.customer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_usages', to='billing.invoice')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='usages', to='billing.offer')),
            ],
            options={
                'db_table': 'offer_usages',
            },
        ),
    ]
