# Generated by Django 5.2.1 on 2026-08-24 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_cart_promo_code_invoice_total_discount_offer_and_more'),
        ('branches', '0002_counter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('expected_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('DISCREPANCY', 'Discrepancy')], default='OPEN', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='shifts', to='branches.branch')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='shifts', to=settings.AUTH_USER_MODEL)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='shifts', to='branches.counter')),
            ],
            options={
                'db_table': 'shifts',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='billing.shift'),
        ),
    ]
