# Generated by Django 5.2.1 on 2026-09-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_shift_invoice_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerequest',
            name='request_type',
            field=models.CharField(choices=[('RETURN', 'Return (Refund to Store Credit)'), ('EXCHANGE', 'Exchange (Swap for another item)')], default='RETURN', max_length=15),
        ),
    ]
