# Generated by Django 5.2.16 on 2026-07-25 04:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('INWARD', 'Inward'), ('OUTWARD', 'Outward'), ('ADJUSTMENT', 'Adjustment'), ('RETURN', 'Return')], max_length=20)),
                ('quantity_change', models.IntegerField()),
                ('resulting_quantity', models.IntegerField()),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='branches.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.product')),
            ],
            options={
                'db_table': 'inventory_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BranchStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stocks', to='branches.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='branch_stocks', to='products.product')),
            ],
            options={
                'db_table': 'branch_stocks',
                'unique_together': {('branch', 'product')},
            },
        ),
    ]
