# Generated by Django 5.2.1 on 2026-07-27 08:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('inventory', '0001_initial'),
        ('products', '0004_product_sku_temporarybulkupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchstock',
            name='reserved_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SerializedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('IN_CART', 'In Cart'), ('SOLD', 'Sold'), ('RETURNED', 'Returned'), ('DEFECTIVE', 'Defective')], default='IN_STOCK', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='serialized_items', to='branches.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='serialized_items', to='products.product')),
            ],
            options={
                'db_table': 'serialized_items',
            },
        ),
    ]
