ROLE_ADMIN = 'ADMIN'
ROLE_SUB_ADMIN = 'SUB_ADMIN'
ROLE_CASHIER = 'CASHIER'
ROLE_STORE_STAFF = 'STORE_STAFF'

ROLE_CHOICES = (
    (ROLE_ADMIN, 'Admin'),
    (ROLE_SUB_ADMIN, 'Sub-Admin'),
    (ROLE_CASHIER, 'Cashier'),
    (ROLE_STORE_STAFF, 'Store Staff'),
)
