# Generated by Django 5.2.1 on 2026-08-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryinward',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
